---
title: "Bayesian regression with chronological uncertainty propagation."
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{BayesReCUP-starthere}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
devtools::load_all()
```

To begin, simulate some data:

```{r}
nintervals <- 1000
times <- 5000:4001
beta <- 0.004
process <- exp(1:nintervals * beta)
nevents <- 1000
nsamples <- 100000
simseqs <- simulateEventCounts(process = process,
                            times = times,
                            nevents = nevents,
                            nsamples = nsamples,
                            bigmatrix = T)

Y <- bigmemory::attach.big.matrix(simseqs$Y)
n <- dim(Y)[1]
x <- cbind(rep(1, n),1:n)

big_matrix_path <- paste(getwd(),"X_desc",sep="/")

bigmemory::filebacked.big.matrix(nrow = n,
                                 ncol = nsamples * dim(x)[2],
                                 backingfile = "X_mat",
                                 backingpath = getwd(),
                                 descriptorfile = "X_desc")

rep_big_x(x, nsamples, big_matrix_path)

X <- bigmemory::attach.big.matrix(paste(getwd(),"X_desc",sep="/"))
```

Then, call the mcmc:

```{r}
startvals <- c(0,0)#rep(0.5, n))
startscales <- c(0.1, 0.0002)# rep(0.05, n))

mcmc_samples_adapt <- regress(Y = Y,
                            X = X,
                            model = "pois",
                            startvals = startvals,
                            scales = startscales,
                            adapt = F)
```
